services:
  prometheus:
    image: prom/prometheus:v2.33.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - loki-network

networks:
  loki-network:
    external: true
