global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: app-tz
    metrics_path: "/metrics"
    static_configs:
      - targets: ["app-tz:8080"]
        labels:
          application: 'my-app'
          instance: 'server-01'
